### ISSUE TITLE
add link of platEMO for convenience.

### ISSUE THREAD

**Issue by anonymone** [yiping0liu/DEA-GNG#1]
Hi, @yiping0liu ,
We're glad you used PlatEMO. 
We have a suggestion, whether you can add a link to the platform. Here are examples.

# DEA-GNG
Copyright 2018-2019 Yiping Liu

This is the code of DEA-GNG proposed in "Yiping Liu, Hisao Ishibuchi, Naoki Masuyama and Yusuke Nojima, Adapting Reference Vectors and Scalarizing Functions by Growing Neural Gas to Handle Irregular Pareto Fronts, IEEE Transactions on Evolutionary Computation, to be published".

The codes use [PlatEMO](https://github.com/BIMK/PlatEMO) published in "Ye Tian et al., PlatEMO: A MATLAB Platform for Evolutionary Multi-Objective Optimization, IEEE Computational Intelligence Magazine, 2017, 12(4): 73-87". 

Please drop all the codes into the main folder of [PlatEMO (v1.6)](https://github.com/BIMK/PlatEMO/releases/tag/v1.6.1). Then Enjoy.

Please contact yiping0liu@gmail.com if you have any problem.

**Comment by yiping0liu** [comment]
Done. Thanks for the suggestion
